# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d20f7bc8d464ad589065b4ffb19f20422dad6190c2aaee6933ecb68900051c0f1a9df1f5e46dcc87f6f5c97510ab3f4b67c33baa8e1bfae6131110f2f817bf

test:
  secret_key_base: a1325dbef62cfd65b615972f7febf381506ec396e1e4dd7eb97a6c831134162169cf02a142b8e28c13d7ab25628217859f3d6d3a3a3603b6445056781bafebb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
